# Generated by Django 4.0.5 on 2022-07-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigosho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigo_mst',
            name='jigo_img',
        ),
        migrations.RemoveField(
            model_name='jigo_mst',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='jigo_mst',
            name='url_width',
        ),
    ]
